-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 11:47:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hw2_wu_peng_spring_2018
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hw2_wu_peng_spring_2018` ;

-- -----------------------------------------------------
-- Schema hw2_wu_peng_spring_2018
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hw2_wu_peng_spring_2018` DEFAULT CHARACTER SET latin1 ;
USE `hw2_wu_peng_spring_2018` ;

-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`person` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`person` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`address` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `street1` VARCHAR(45) NULL DEFAULT NULL,
  `street2` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `primary` TINYINT(4) NULL DEFAULT NULL,
  `address_person_gen` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `address_person_generalization`
    FOREIGN KEY (`address_person_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`developer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`developer` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`developer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `developerKey` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `developer_person_generalization`
    FOREIGN KEY (`id`)
    REFERENCES `hw2_wu_peng_spring_2018`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`website` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`website` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `created` DATE NULL DEFAULT NULL,
  `updataed` DATE NULL DEFAULT NULL,
  `visits` INT(11) NULL DEFAULT NULL,
  `website_dev_gen` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `website_dev_gen_idx` (`website_dev_gen` ASC),
  CONSTRAINT `website_dev_gen`
    FOREIGN KEY (`website_dev_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`developer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`page` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`page` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `created` DATE NULL DEFAULT NULL,
  `update` DATE NULL DEFAULT NULL,
  `views` INT(11) NULL DEFAULT NULL,
  `page_website_gen` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `page_website_gen_idx` (`page_website_gen` ASC),
  CONSTRAINT `page_website_gen`
    FOREIGN KEY (`page_website_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`website` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`widget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`widget` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`widget` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `width` INT(11) NULL DEFAULT NULL,
  `height` INT(11) NULL DEFAULT NULL,
  `cssClass` VARCHAR(45) NULL DEFAULT NULL,
  `cssStyple` VARCHAR(45) NULL DEFAULT NULL,
  `text` VARCHAR(45) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `widget_page_gen` INT NULL,
  INDEX `widget_page_generalization_idx` (`widget_page_gen` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `widget_page_generalization`
    FOREIGN KEY (`widget_page_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`page` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`heading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`heading` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`heading` (
  `id` INT(11) NOT NULL,
  `size` INT(11) NULL DEFAULT NULL,
  INDEX `heading_widget_generalization_idx` (`id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `heading_widget_generalization`
    FOREIGN KEY (`id`)
    REFERENCES `hw2_wu_peng_spring_2018`.`widget` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`html`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`html` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`html` (
  `id` INT(11) NOT NULL,
  `html` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `html_widget_generalization_idx` (`id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `html_widget_generalization`
    FOREIGN KEY (`id`)
    REFERENCES `hw2_wu_peng_spring_2018`.`widget` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`image` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`image` (
  `id` INT(11) NOT NULL,
  `src` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `image_widget_generalization`
    FOREIGN KEY (`id`)
    REFERENCES `hw2_wu_peng_spring_2018`.`widget` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`pagePriviledge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`pagePriviledge` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`pagePriviledge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `priviledge` ENUM('create', 'read', 'update', 'delete') NULL DEFAULT NULL,
  `pagePriviledge_dev_gen` INT NULL,
  `pagePriviledge_page_gen` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `pagePriviledge_page_gen_idx` (`pagePriviledge_page_gen` ASC),
  INDEX `pagePriviledge_dev_gen_idx` (`pagePriviledge_dev_gen` ASC),
  CONSTRAINT `pagePriviledge_page_gen`
    FOREIGN KEY (`pagePriviledge_page_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `pagePriviledge_dev_gen`
    FOREIGN KEY (`pagePriviledge_dev_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`developer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`pageRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`pageRole` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`pageRole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` ENUM('owner', 'admin', 'writer', 'editor', 'reviewer') NULL DEFAULT NULL,
  `pageRole_dev_gen` INT NULL,
  `pageRole_page_gen` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `pageRole_page_gen_idx` (`pageRole_page_gen` ASC),
  INDEX `pageRole_dev_gen_idx` (`pageRole_dev_gen` ASC),
  CONSTRAINT `pageRole_page_gen`
    FOREIGN KEY (`pageRole_page_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `pageRole_dev_gen`
    FOREIGN KEY (`pageRole_dev_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`developer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`phone` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`phone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `primary` TINYINT(4) NULL DEFAULT NULL,
  `phone_person_gen` INT NULL,
  INDEX `phone_person_generalization_idx` (`phone_person_gen` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `phone_person_generalization`
    FOREIGN KEY (`phone_person_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`user` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userAgreement` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_person_generalization`
    FOREIGN KEY (`id`)
    REFERENCES `hw2_wu_peng_spring_2018`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`websitePriviledge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`websitePriviledge` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`websitePriviledge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `priviledge` ENUM('create', 'read', 'update', 'delete') NULL DEFAULT NULL,
  `websitePriviledge_dev_gen` INT NULL,
  `websitePriviledge_web_gen` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `websitePriviledge_web_gen_idx` (`websitePriviledge_web_gen` ASC),
  INDEX `websitePriviledge_dev_gen_idx` (`websitePriviledge_dev_gen` ASC),
  CONSTRAINT `websitePriviledge_web_gen`
    FOREIGN KEY (`websitePriviledge_web_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `websitePriviledge_dev_gen`
    FOREIGN KEY (`websitePriviledge_dev_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`developer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`websiteRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`websiteRole` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`websiteRole` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` ENUM('owner', 'admin', 'writer', 'editor', 'reviewer') NULL DEFAULT NULL,
  `websiteRole_web_gen` INT(11) NULL DEFAULT NULL,
  `websitRole_deve_gen` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `websiteRole_web_gen_idx` (`websiteRole_web_gen` ASC),
  INDEX `websiteRole_dev_gen_idx` (`websitRole_deve_gen` ASC),
  CONSTRAINT `websiteRole_web_gen`
    FOREIGN KEY (`websiteRole_web_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `websiteRole_dev_gen`
    FOREIGN KEY (`websitRole_deve_gen`)
    REFERENCES `hw2_wu_peng_spring_2018`.`developer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hw2_wu_peng_spring_2018`.`youtube`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw2_wu_peng_spring_2018`.`youtube` ;

CREATE TABLE IF NOT EXISTS `hw2_wu_peng_spring_2018`.`youtube` (
  `id` INT(11) NOT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  `sharable` TINYINT(4) NULL DEFAULT NULL,
  `expandable` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `youtube_widget_generalization`
    FOREIGN KEY (`id`)
    REFERENCES `hw2_wu_peng_spring_2018`.`widget` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
